//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesertRage.Resources.Media.Images.Menu.Skills {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Skills {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skills() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesertRage.Resources.Media.Images.Menu.Skills.Skills", typeof(Skills).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Analyze.svg.
        /// </summary>
        public static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/AttackUp.svg.
        /// </summary>
        public static string AttackUp {
            get {
                return ResourceManager.GetString("AttackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Combo.svg.
        /// </summary>
        public static string Combo {
            get {
                return ResourceManager.GetString("Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Cure.svg.
        /// </summary>
        public static string Cure {
            get {
                return ResourceManager.GetString("Cure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Cure2.svg.
        /// </summary>
        public static string Cure2 {
            get {
                return ResourceManager.GetString("Cure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/DefenceUp.svg.
        /// </summary>
        public static string DefenceUp {
            get {
                return ResourceManager.GetString("DefenceUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Heal.svg.
        /// </summary>
        public static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Slide.svg.
        /// </summary>
        public static string Slide {
            get {
                return ResourceManager.GetString("Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Slingshot.svg.
        /// </summary>
        public static string Slingshot {
            get {
                return ResourceManager.GetString("Slingshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Storm.svg.
        /// </summary>
        public static string Storm {
            get {
                return ResourceManager.GetString("Storm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Torch.svg.
        /// </summary>
        public static string Torch {
            get {
                return ResourceManager.GetString("Torch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Resources/Media/Images/Menu/Skills/Whip.svg.
        /// </summary>
        public static string Whip {
            get {
                return ResourceManager.GetString("Whip", resourceCulture);
            }
        }
    }
}
