//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesertRage.Resources.Media.OST.Sounds.Defeat.Enemies {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnemyDefeat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnemyDefeat() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesertRage.Resources.Media.OST.Sounds.Defeat.Enemies.EnemyDefeat", typeof(EnemyDefeat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Bones.mp3.
        /// </summary>
        public static string Bones {
            get {
                return ResourceManager.GetString("Bones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Ghoul.mp3.
        /// </summary>
        public static string Ghoul {
            get {
                return ResourceManager.GetString("Ghoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/GrimReaper.mp3.
        /// </summary>
        public static string GrimReaper {
            get {
                return ResourceManager.GetString("GrimReaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Imp.mp3.
        /// </summary>
        public static string Imp {
            get {
                return ResourceManager.GetString("Imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/KillerMole.mp3.
        /// </summary>
        public static string KillerMole {
            get {
                return ResourceManager.GetString("KillerMole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Master.mp3.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Mummy.mp3.
        /// </summary>
        public static string Mummy {
            get {
                return ResourceManager.GetString("Mummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Scarab.mp3.
        /// </summary>
        public static string Scarab {
            get {
                return ResourceManager.GetString("Scarab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Spider.mp3.
        /// </summary>
        public static string Spider {
            get {
                return ResourceManager.GetString("Spider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Vulture.mp3.
        /// </summary>
        public static string Vulture {
            get {
                return ResourceManager.GetString("Vulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Worm.mp3.
        /// </summary>
        public static string Worm {
            get {
                return ResourceManager.GetString("Worm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resources/Media/OST/Sounds/Defeat/Enemies/Zombie.mp3.
        /// </summary>
        public static string Zombie {
            get {
                return ResourceManager.GetString("Zombie", resourceCulture);
            }
        }
    }
}
